# Generated by Django 3.2 on 2021-08-22 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money_next_month', models.PositiveSmallIntegerField()),
                ('wage', models.PositiveSmallIntegerField()),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.PositiveSmallIntegerField()),
                ('name', models.CharField(max_length=120)),
                ('family', models.CharField(max_length=120)),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_ratio', models.PositiveSmallIntegerField(default=2)),
                ('number_months_loan_repayment', models.PositiveSmallIntegerField(default=20)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fund', models.IntegerField(default=200000)),
                ('loan_p', models.IntegerField()),
                ('payer_name', models.CharField(max_length=120)),
                ('status_transaction', models.CharField(choices=[('receive_money', 'دریافت وجه'), ('loan_repayment', 'پرداخت وام')], default='receive_money', max_length=15)),
                ('open_account', models.BooleanField(default=False)),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('members', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dashboard.members')),
            ],
        ),
        migrations.CreateModel(
            name='PeriodLoan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_loan', models.PositiveSmallIntegerField(unique=True)),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('members', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dashboard.members')),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_loan', models.BooleanField(default=False)),
                ('receive_loan', models.PositiveSmallIntegerField()),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('members', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dashboard.members')),
                ('period_loan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dashboard.periodloan')),
            ],
        ),
        migrations.CreateModel(
            name='ListPaymentCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_bank', models.IntegerField()),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('payment_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.members')),
            ],
        ),
    ]
