# Generated by Django 3.2 on 2021-08-26 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='members',
            unique_together={('name', 'family')},
        ),
    ]
