# Generated by Django 3.2 on 2022-03-13 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_members_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='Fund',
            field=models.CharField(default=200000, max_length=120),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='loan_p',
            field=models.CharField(max_length=120),
        ),
    ]
