# Generated by Django 3.2 on 2022-03-13 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20220313_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='members',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.members'),
        ),
    ]
