# Generated by Django 3.2 on 2022-03-13 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_transaction_members'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fund', models.CharField(default=200000, max_length=120)),
                ('loan_p', models.CharField(max_length=120)),
                ('payer_name', models.CharField(max_length=120)),
                ('status_transaction', models.CharField(choices=[('receive_money', 'دریافت وجه'), ('loan_repayment', 'پرداخت وام')], default='receive_money', max_length=15)),
                ('open_account', models.BooleanField(default=False)),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('members', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.members')),
            ],
        ),
    ]
