# Generated by Django 3.2 on 2022-03-13 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_transaction2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transaction2',
        ),
    ]
