# Generated by Django 3.2 on 2022-03-19 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_delete_transaction2'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='minimum_share',
            field=models.PositiveSmallIntegerField(default=20),
        ),
    ]
