# Generated by Django 3.2 on 2022-03-19 21:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_setting_minimum_share'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='setting',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='setting',
            name='minimum_share',
            field=models.PositiveSmallIntegerField(default=200000),
        ),
    ]
