# Generated by Django 3.2 on 2022-03-24 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_auto_20220320_0055'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='maximum_loan',
            field=models.PositiveSmallIntegerField(default=100000000),
            preserve_default=False,
        ),
    ]
