# Generated by Django 3.2 on 2022-03-24 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_setting_maximum_loan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='loan_ratio',
            field=models.FloatField(default=2),
        ),
    ]
