# Generated by Django 3.2 on 2022-03-25 10:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_alter_setting_loan_ratio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='last_loan',
        ),
        migrations.AddField(
            model_name='loan',
            name='date_receive_loan',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='periodloan',
            name='is_receive_loan',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
