# Generated by Django 3.2 on 2022-03-25 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_auto_20220325_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periodloan',
            name='is_receive_loan',
            field=models.BooleanField(default=False),
        ),
    ]
