# Generated by Django 3.2 on 2022-03-25 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_alter_periodloan_is_receive_loan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='period_loan',
        ),
    ]
