# Generated by Django 3.2 on 2022-03-25 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_remove_loan_period_loan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cash',
            old_name='money_next_month',
            new_name='money_before_month',
        ),
        migrations.RenameField(
            model_name='cash',
            old_name='wage',
            new_name='total_wage',
        ),
        migrations.AddField(
            model_name='cash',
            name='wage_before_month',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
