# Generated by Django 3.2 on 2022-03-29 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_loan_installment_loans'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='installment_loans',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
