# Generated by Django 3.2 on 2022-08-04 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_alter_loan_installment_loans'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cash',
            name='wage_before_month',
        ),
        migrations.AddField(
            model_name='cash',
            name='cashier_fee',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cash',
            name='fund_fee',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='loan',
            name='remaining_installments',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cash',
            name='money_before_month',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cash',
            name='total_wage',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='loan',
            name='receive_loan',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
