# Generated by Django 3.2 on 2022-08-04 16:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_auto_20220804_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='cash',
            name='submit_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
